# Generated by Django 4.2.6 on 2023-10-23 10:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01', verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(default=accounts.models.generate_pseudonym, max_length=50, unique=True, verbose_name='Pseudonyme'),
        ),
    ]
